from disjointset import bounded_path_compression_rank
from disjointset.abstract import *
from disjointset.linked_list import *

BoundedDisjointSetPathCompressionAndRank = bounded_path_compression_rank.BoundedDisjointSetPathCompressionAndRank
